# Site settings
title: 宝爸的轻博客
email: yubo.yue@163.com
description: "Keep looking, Don't settled"
baseurl: ""
url: "http://yubo-yue.github.io"

# Build settings
markdown: kramdown
permalink: pretty


kramdown:
  input: GFM