# Site settings
title: 大宝的Daddy 
email: yubo.yue@163.com
description: "Keep looking, Don't settled"
baseurl: ""
url: "http://yubo-yue.github.io"

# Build settings
markdown: kramdown
permalink: pretty


#markdown processor
redcarpet: 
extensions: ["no_intra_emphasis", "no_fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]


