# Site settings
title: Yubo Yue's Knowledge Repository
email: yubo.yue@163.com
description: "Keep looking, Don't settled"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
